name: Lint
on: push
jobs:
  lint:
    name: Lint
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download sigcheck.exe
        run: |
          Invoke-WebRequest -Uri 'https://live.sysinternals.com/sigcheck.exe' -OutFile 'sigcheck.exe'

      - name: Download rcedit
        run: |
          Invoke-WebRequest -Uri https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe -OutFile rcedit.exe
      - name: Edit metadata
        run: |
          ./rcedit.exe "./percy.exe"
          --set-version-string CompanyName "BrowserStack Inc." \
          --set-version-string FileDescription "Percy CLI Binary" \
          --set-version-string FileVersion "1.28.8" \
          --set-version-string InternalName "PercyCLI" \
          --set-version-string LegalCopyright "Copyright BrowserStack Limited" \
          --set-version-string OriginalFilename "PercyCLI" \
          --set-version-string ProductName "PercyCLI" \
          --set-version-string ProductVersion "1.28.8"

      # - name: Upload win artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: percy.exe
      #     path: percy.exe
      - name: Debug file system
        run: |
          dir  # List directory contents for debugging
      - name: Check executable with sigcheck
        shell: cmd
        run: |
          .\sigcheck.exe -accepteula -q -a -i "./percy.exe"
