name: Lint
on: push
jobs:
  lint:
    name: Lint
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Resource Hacker
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://www.angusj.com/resourcehacker/resource_hacker.zip -OutFile resource_hacker.zip
          Expand-Archive -Path resource_hacker.zip -DestinationPath ./resource_hacker

      - name: Create resource script
        shell: pwsh
        run: |
          echo 1 VERSIONINFO > versioninfo.rc
          echo FILEVERSION 1,0,0,0 >> versioninfo.rc
          echo PRODUCTVERSION 1,0,0,0 >> versioninfo.rc
          echo BEGIN >> versioninfo.rc
          echo   BLOCK "StringFileInfo" >> versioninfo.rc
          echo   BEGIN >> versioninfo.rc
          echo     BLOCK "040904b0" >> versioninfo.rc
          echo     BEGIN >> versioninfo.rc
          echo       VALUE "CompanyName", "Your Company" >> versioninfo.rc
          echo       VALUE "FileDescription", "Your Application Description" >> versioninfo.rc
          echo       VALUE "FileVersion", "1.0.0.0" >> versioninfo.rc
          echo       VALUE "InternalName", "YourApp" >> versioninfo.rc
          echo       VALUE "LegalCopyright", "© Your Company 2024" >> versioninfo.rc
          echo       VALUE "OriginalFilename", "YourApp.exe" >> versioninfo.rc
          echo       VALUE "ProductName", "Your Product" >> versioninfo.rc
          echo       VALUE "ProductVersion", "1.0.0.0" >> versioninfo.rc
          echo     END >> versioninfo.rc
          echo   END >> versioninfo.rc
          echo   BLOCK "VarFileInfo" >> versioninfo.rc
          echo   BEGIN >> versioninfo.rc
          echo     VALUE "Translation", 0x409, 1200 >> versioninfo.rc
          echo   END >> versioninfo.rc
          echo END >> versioninfo.rc

      - name: Compile resource script
        shell: pwsh
        run: |
          ./resource_hacker/ResourceHacker.exe -compile versioninfo.rc -save versioninfo.res

      - name: Update executable
        shell: pwsh
        run: |
          ./resource_hacker/ResourceHacker.exe -open percy.exe -save percy.exe -action addoverwrite -res versioninfo.res
          ./resource_hacker/ResourceHacker.exe -open percy.exe -save percy.exe -action addoverwrite -mask ICONGROUP,MAINICON -res icon.ico
      - name: Upload win artifact
        uses: actions/upload-artifact@v4
        with:
          name: percy.exe
          path: percy.exe
