name: Lint
on: push
jobs:
  lint:
    name: Lint
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Download sigcheck.exe
      #   run: |
      #     Invoke-WebRequest -Uri 'https://live.sysinternals.com/sigcheck.exe' -OutFile 'sigcheck.exe'

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'

      # - name: Install Dependencies
      #   run: pip install pefile

      # - name: Update EXE Metadata
      #   run: python update.py ./percy.exe
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you need

      # - name: Install rcedit
      #   run: npm install rcedit

      # - name: Update EXE Metadata
      #   run: |
      #     node -e "const rcedit = require('rcedit'); rcedit('percy_2.exe', { icon: 'percy.ico', 'version-string': { ProductName: 'Your Product Name', FileDescription: 'Your File Description', ProductVersion: '1.0.0', FileVersion: '1.0.0', CompanyName: 'Your Company Name' } }, function(err) { if (err) { console.error(err); process.exit(1); } console.log('Metadata updated successfully'); });"

      # - name: Download Resource Hacker
      #   run: |
      #     Invoke-WebRequest -Uri 'http://www.angusj.com/resourcehacker/resource_hacker.zip' -OutFile 'resource_hacker.zip'
      #     Expand-Archive -Path resource_hacker.zip -DestinationPath ./resource_hacker

      # - name: Update EXE Metadata and Icon
      #   run: |
      #     ./resource_hacker/ResourceHacker.exe -open percy.exe -save new.exe -action addoverwrite -res versioninfo.rc

      # - name: Download rcedit
      #   run: |
      #     Invoke-WebRequest -Uri https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x86.exe -OutFile rcedit.exe
      # - name: Edit metadata
      #   run: |
      #     ./rcedit.exe "./percy.exe" --set-icon "./app/percy.ico"
      - name: Debug file system
        run: |
          ./node-v14.20.0/vcbuild.bat
      # - name: Verify executable
      #   run: ./percy.exe --version
      # - name: Upload win artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: percy.exe
      #     path: percy.exe

      # - name: Check executable with sigcheck
      #   shell: cmd
      #   run: |
      #     .\sigcheck.exe -accepteula -q -a -i "percy.exe"
